# Message type definitions
MESSAGE_TYPES = {
    # Client -> Server
    'REGISTER': 'REGISTER',
    'LOGIN': 'LOGIN',
    'SEND_MESSAGE': 'SEND_MESSAGE',
    'CREATE_GROUP': 'CREATE_GROUP',
    'JOIN_GROUP': 'JOIN_GROUP',
    'LEAVE_GROUP': 'LEAVE_GROUP',
    'GET_GROUP_MEMBERS': 'GET_GROUP_MEMBERS',
    'ADD_GROUP_MEMBER': 'ADD_GROUP_MEMBER',
    'HEARTBEAT': 'HEARTBEAT',
    'FILE_TRANSFER': 'FILE_TRANSFER',
    'FILE_REQUEST': 'FILE_REQUEST',
    'RECALL_MESSAGE': 'RECALL_MESSAGE',

    # Server -> Client
    'REGISTER_RESPONSE': 'REGISTER_RESPONSE',
    'LOGIN_RESPONSE': 'LOGIN_RESPONSE',
    'MESSAGE': 'MESSAGE',
    'GROUP_CREATED': 'GROUP_CREATED',
    'GROUP_JOINED': 'GROUP_JOINED',
    'GROUP_LEFT': 'GROUP_LEFT',
    'GROUP_LIST': 'GROUP_LIST',
    'USER_LIST': 'USER_LIST',
    'GROUP_MEMBERS': 'GROUP_MEMBERS',
    'GROUP_MEMBER_ADDED': 'GROUP_MEMBER_ADDED',
    'GROUP_HISTORY_SYNC': 'GROUP_HISTORY_SYNC',
    'USER_STATUS': 'USER_STATUS',
    'GROUP_STATUS': 'GROUP_STATUS',
    'HEARTBEAT_RESPONSE': 'HEARTBEAT_RESPONSE',
    'FILE_TRANSFER_RESPONSE': 'FILE_TRANSFER_RESPONSE',
    'FILE_DATA': 'FILE_DATA',
    'RECALL_RESPONSE': 'RECALL_RESPONSE',
    'ERROR': 'ERROR',
}

STATUS = {
    'ONLINE': 'ONLINE',
    'OFFLINE': 'OFFLINE',
}
